name: Nova CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Invoice API Test
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14-alpine
        env:
          #credentials for CI 
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin@256
          POSTGRES_DB: voucherdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    env:
      # CI-specific environment variables
      DATABASE_URL: postgresql://postgres:admin%40256@localhost:5432/voucherdb
      # NODE_ENV: test
      # SECRET_KEY: test_jwt_secret_for_ci_only
      # credentials for CI tests
      CLOUD_NAME: test_cloud
      CLOUDINARY_API_KEY: test_key
      CLOUDINARY_API_SECRET: test_secret
      EMAIL_USER: test@example.com
      EMAIL_PASS: test_password
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Prisma migrations
        run: npx prisma migrate deploy

      # - name: Seed test user
      #   run: node prisma/seed.js
      
      - name: Run tests
        run: npm test


